services:
  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - 5433:5433
    restart: unless-stopped
    volumes:
    - horilla-data:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -U
      - postgres
      interval: 10s
      timeout: 5s
      retries: 5
  pppddd:
    image: hr
    container_name: pppddd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 9000:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5433/pppddd
    command: ./entrypoint.sh
    volumes:
    - ./horilla:/app/horilla
    depends_on:
      db:
        condition: service_healthy
  pppproject:
    image: hr
    container_name: pppproject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 9001:8000
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5433/pppproject
    command: ./entrypoint.sh
    volumes:
    - ./horilla:/pppproject/horilla
    - /var/www/horilla/pppproject/staticfiles:/pppproject/staticfiles
    - /var/www/horilla/pppproject/media:/pppproject/media
    depends_on:
      db:
        condition: service_healthy
volumes:
  horilla-data: null
